### ISSUE TITLE
尝试跑起so的时候出现了如下错误

### ISSUE THREAD

**Issue by oMengLvRong** [maiyao1988/ExAndroidNativeEmu#11]
贴出错误信息如下：

hook_id:65314, hook_func:<bound method native_method.<locals>.native_method_wrapper of <androidemu.java.jni_env.JNIEnv object at 0x0000019B77784408>>
2020-03-19 09:50:21,236   DEBUG            androidemu.java.jni_env | JNIEnv->GetMethodId(4097, getBytes, (Ljava/lang/String;)[B) was called
Traceback (most recent call last):
  File "D:\python_project\ExAndroidNativeEmu\androidemu\hooker.py", line 100, in _hook
    hook_func(self._emu)
  File "D:\python_project\ExAndroidNativeEmu\androidemu\java\helpers\native_method.py", line 113, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "D:\python_project\ExAndroidNativeEmu\androidemu\java\jni_env.py", line 671, in get_method_id
    method = clazz.value.find_method(name, sig)
AttributeError: type object 'str' has no attribute 'find_method'

**Comment by maiyao1988** [comment]
把so提供一下，跑的是什么函数。

**Comment by oMengLvRong** [comment]
链接：https://pan.baidu.com/s/1oQiJQIVvtm9okqo_wwUG9g 
提取码：f7rf

跑的jni_onload, py文件里我补充了一个Java函数

**Comment by maiyao1988** [comment]
ok.我晚点看看

**Comment by oMengLvRong** [comment]
8.5

**Comment by maiyao1988** [comment]
这是由于jstring没有实现GetMethodId语义，没有将jstring也当成一个java对象导致的。

**Comment by oMengLvRong** [comment]
我觉得也是类似的问题。。但是在项目里面该怎么修改？

**Comment by maiyao1988** [comment]
> 我觉得也是类似的问题。。但是在项目里面该怎么修改？

我在改。

**Comment by maiyao1988** [comment]
最新新版已经fix，但是example_douyin.py的类型需要作出修改，详见项目中的example_douyin.py,
so还没跑起来由于so用到的java类型缺失，需要实现所需的java类。

**Comment by maiyao1988** [comment]
@oMengLvRong 可以提供一下这个so所属的apk吗？

**Comment by oMengLvRong** [comment]
链接：https://pan.baidu.com/s/15Q6MqUY1AjPwYgo-SNSlCQ 
提取码：esex 

-------
项目最新版是对so实现分析了吗？还是再需要自行添加些系统调用/函数？

**Comment by maiyao1988** [comment]
最新版本加入了部分java类和系统调用，但是还没能正常模拟这个so，需要继续改进

**Comment by maiyao1988** [comment]
该issue提的问题已经解决，关于这个cms的兼容转另外一个issue #14
