### ISSUE TITLE
Need help for getUserInfo() function

### ISSUE THREAD

**Issue by playniuniu** [maiyao1988/ExAndroidNativeEmu#19]
Version 8.5 also need **as**, **cp**, **mas** arguments to do http request

**as** and **cp** are generate by **com.ss.android.common.applog.UserInfo.getUserInfo()** function

I user ExAndroidEmu to run this function, but the result is not same as real package capture result

I create a gist here  [https://gist.github.com/playniuniu/dd4140f26cb6d4aff89982624ba47043](https://gist.github.com/playniuniu/dd4140f26cb6d4aff89982624ba47043)

The exandoridemu result is: **a0100ffee45e8deaa0100fff34100ffee4100fff2c30**

but real result is: **aad1d780985e8dd408d1d780e8d1d78098d1d780e038**

I thought I do something wrong with **Array("java.lang.String")**

Could you help me with how to create  **[]String** in exandroidemu please?

Thanks

**Comment by maiyao1988** [comment]
It mays have no relationship with the simulation, Have you ever test on the real machine with the same parameters? I notice that each time I call leviathan on the real dy enviroment, the result is different, dy may introduce some random factor into this method, not sure if it is true in userinfo.
