### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by kingking888** [maiyao1988/ExAndroidNativeEmu#2]
Connected to pydev debugger (build 193.5662.61)
map addr:0x10000000, end:0x10100000, sz:0x00100000 off=0x00000000
stack addr 10100000
map addr:0x01000000, end:0x01200000, sz:0x00200000 off=0x00000000
2020-02-16 12:01:45,819   DEBUG        androidemu.internal.modules | Loading module 'tests/bin/libcms.so'.
map addr:0xCBBCB000, end:0xCBCA8627, sz:0x000DD627 off=0x00000000
map addr:0xCBCA9000, end:0xCBCA9000, sz:0x00000000 off=0x00000000
map addr:0xCBCA9000, end:0xCBCB304C, sz:0x0000A04C off=0x000DD000
map addr:0xCBCB4000, end:0xCBCBB000, sz:0x00007000 off=0x00000000
2020-02-16 12:01:52,875   DEBUG        androidemu.internal.modules | Loading module 'D:/Python_Projects/AndroidProjects/ExAndroidNativeEmu/vfs/system/lib/'.
Traceback (most recent call last):
  File "D:\Python_Projects\AndroidProjects\ExAndroidNativeEmu\androidemu\internal\modules.py", line 207, in load_module
    libmod = self.load_module(path)
  File "D:\Python_Projects\AndroidProjects\ExAndroidNativeEmu\androidemu\internal\modules.py", line 77, in load_module
    with open(filename, 'rb') as fstream:
PermissionError: [Errno 13] Permission denied: 'D:/Python_Projects/AndroidProjects/ExAndroidNativeEmu/vfs/system/lib/'

**Comment by maiyao1988** [comment]
> Connected to pydev debugger (build 193.5662.61)
> map addr:0x10000000, end:0x10100000, sz:0x00100000 off=0x00000000
> stack addr 10100000
> map addr:0x01000000, end:0x01200000, sz:0x00200000 off=0x00000000
> 2020-02-16 12:01:45,819 DEBUG androidemu.internal.modules | Loading module 'tests/bin/libcms.so'.
> map addr:0xCBBCB000, end:0xCBCA8627, sz:0x000DD627 off=0x00000000
> map addr:0xCBCA9000, end:0xCBCA9000, sz:0x00000000 off=0x00000000
> map addr:0xCBCA9000, end:0xCBCB304C, sz:0x0000A04C off=0x000DD000
> map addr:0xCBCB4000, end:0xCBCBB000, sz:0x00007000 off=0x00000000
> 2020-02-16 12:01:52,875 DEBUG androidemu.internal.modules | Loading module 'D:/Python_Projects/AndroidProjects/ExAndroidNativeEmu/vfs/system/lib/'.
> Traceback (most recent call last):
> File "D:\Python_Projects\AndroidProjects\ExAndroidNativeEmu\androidemu\internal\modules.py", line 207, in load_module
> libmod = self.load_module(path)
> File "D:\Python_Projects\AndroidProjects\ExAndroidNativeEmu\androidemu\internal\modules.py", line 77, in load_module
> with open(filename, 'rb') as fstream:
> PermissionError: [Errno 13] Permission denied: 'D:/Python_Projects/AndroidProjects/ExAndroidNativeEmu/vfs/system/lib/'
This logic is supposed to be getting elf dependency name and load it.

This is maybe a bug on Windows when getting dependency so name.I don't have Windows enviroment right now, you can add some printing at modules.py line 198 to see if the so_name getting right on windows. this is supposed to be some lib name like 'libc.so', it is likely getting empty string on windows.

**Comment by ccnie** [comment]
Tried both of these two example 'example_jni' and 'example_douyin' on Windows 10 Pro

debug crashed in method load_module

...
so_needed = []
for str_off in dt_needed:
	str_addr = dynstr_addr + str_off
	so_name = memory_helpers.read_utf8(self.emu.mu, str_addr)
	so_needed.append(so_name)
...
	
dt_needed <class 'list'>: [8130, 8140, 8121, 19]

self.emu.mu	<unicorn.unicorn.Uc object at 0x000001BB614350F0>

all of so_names read from mu are null character

**Comment by maiyao1988** [comment]
> Tried both of these two example 'example_jni' and 'example_douyin' on Windows 10 Pro
> 
> debug crashed in method load_module
> 
> ...
> so_needed = []
> for str_off in dt_needed:
> str_addr = dynstr_addr + str_off
> so_name = memory_helpers.read_utf8(self.emu.mu, str_addr)
> so_needed.append(so_name)
> ...
> 
> dt_needed <class 'list'>: [8130, 8140, 8121, 19]
> 
> self.emu.mu	<unicorn.unicorn.Uc object at 0x000001BB614350F0>
> 
> all of so_names read from mu are null character

ok, I will find a windows pc, reproduce and fix it.

**Comment by maiyao1988** [comment]
a72dc66 has fixed this issue
