### ISSUE TITLE
想跑vx一个接口跑不起来

### ISSUE THREAD

**Issue by linhere20** [maiyao1988/ExAndroidNativeEmu#21]
大佬，我用你这个项目想跑vx libwechatnormsg里的SignRqtBufByAutoChosenKey函数，但是应该是在load_library的时候就出错了.
`emulator.load_library("tests/bin/libwechatnormsg.so")`

期间出过几个systemcall调用未实现的错误，我参考现在的写法实现了一下，可能实现的不对，后面抛出的异常不知道怎么处理，太菜了，大佬能帮忙提供一下思路吗？

diff和so：[归档.zip](https://github.com/maiyao1988/ExAndroidNativeEmu/files/4459827/default.zip)

----------
错误信息：

> 12676 - 2020-04-10 11:37:45,979 - INFO - syscall 220 lr=0xCBD02C9F
12676 - 2020-04-10 11:37:45,979 - DEBUG - Executing syscall madvise(0x302C3000, 0x0000001C, 0x0000000C) at 0xCBD104CC
12676 - 2020-04-10 11:37:45,979 - INFO - syscall 126 lr=0xCBD01F1D
12676 - 2020-04-10 11:37:45,980 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0DDC) at 0xCBD110F0
12676 - 2020-04-10 11:37:45,980 - INFO - syscall 67 lr=0xCBD01F43
12676 - 2020-04-10 11:37:45,980 - DEBUG - Executing syscall sigaction(0x00000006, 0x100F0DE0, 0x100F0DE0) at 0xCBD110D0
12676 - 2020-04-10 11:37:45,980 - WARNING - sa_handler [0x00000000] sa_mask [0x00000000] sa_flag [0x10000000] sa_restorer [0x100F0E14]
12676 - 2020-04-10 11:37:45,980 - INFO - syscall 126 lr=0xCBD01F4D
12676 - 2020-04-10 11:37:45,980 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0DDC) at 0xCBD110F0
12676 - 2020-04-10 11:37:45,981 - INFO - syscall 248 lr=0xCBD01F59
12676 - 2020-04-10 11:37:45,981 - DEBUG - Executing syscall faccessat(0x00000001, 0x00000000, 0x00000001, 0x00000000) at 0xCBD0FD68
12676 - 2020-04-10 11:37:45,981 - INFO - faccessat filename:[]
12676 - 2020-04-10 11:37:45,982 - INFO - syscall 5 lr=0xCBD1D761
12676 - 2020-04-10 11:37:45,982 - DEBUG - Executing syscall open(0xCBD2FD4A, 0x000A0001, 0x00000000) at 0xCBD10358
12676 - 2020-04-10 11:37:45,982 - INFO - File opened '/dev/log/main'
12676 - 2020-04-10 11:37:45,982 - INFO - openat return fd 15
12676 - 2020-04-10 11:37:45,982 - INFO - syscall 146 lr=0xCBD02441
12676 - 2020-04-10 11:37:45,983 - DEBUG - Executing syscall writev(0x0000000F, 0x100F0958, 0x00000003) at 0xCBD105CC
12676 - 2020-04-10 11:37:45,983 - INFO - Writev b'\x07'
12676 - 2020-04-10 11:37:45,983 - INFO - Writev b'libc\x00'
12676 - 2020-04-10 11:37:45,988 - INFO - Writev b':0: assertion "" failed\x00'
12676 - 2020-04-10 11:37:45,988 - INFO - syscall 6 lr=0xCBD02457
12676 - 2020-04-10 11:37:45,988 - DEBUG - Executing syscall close(0x0000000F) at 0xCBD1039C
12676 - 2020-04-10 11:37:45,988 - INFO - syscall 192 lr=0xCBD02C83
12676 - 2020-04-10 11:37:45,989 - DEBUG - Executing syscall mmap2(0x00000000, 0x0000001C, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBD1042C
map addr:0x00000000, end:0x0000001C, sz:0x0000001C off=0x00000000
before mem_map addr:0x302C4000, sz:0x00001000
mmap return 0x302C4000
12676 - 2020-04-10 11:37:46,136 - INFO - syscall 220 lr=0xCBD02C9F
12676 - 2020-04-10 11:37:46,136 - DEBUG - Executing syscall madvise(0x302C4000, 0x0000001C, 0x0000000C) at 0xCBD104CC
12676 - 2020-04-10 11:37:46,136 - INFO - syscall 126 lr=0xCBD01F1D
12676 - 2020-04-10 11:37:46,136 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0D84) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,137 - INFO - syscall 67 lr=0xCBD01F43
12676 - 2020-04-10 11:37:46,137 - DEBUG - Executing syscall sigaction(0x00000006, 0x100F0D88, 0x100F0D88) at 0xCBD110D0
12676 - 2020-04-10 11:37:46,137 - WARNING - sa_handler [0x00000000] sa_mask [0x00000000] sa_flag [0x10000000] sa_restorer [0x100F0DBC]
12676 - 2020-04-10 11:37:46,138 - INFO - syscall 126 lr=0xCBD01F4D
12676 - 2020-04-10 11:37:46,138 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0D84) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,139 - INFO - syscall 248 lr=0xCBD01F59
12676 - 2020-04-10 11:37:46,139 - DEBUG - Executing syscall faccessat(0x00000001, 0x00000000, 0x00000001, 0x00000000) at 0xCBD0FD68
12676 - 2020-04-10 11:37:46,139 - INFO - faccessat filename:[]
12676 - 2020-04-10 11:37:46,140 - INFO - syscall 5 lr=0xCBD1D761
12676 - 2020-04-10 11:37:46,140 - DEBUG - Executing syscall open(0xCBD2FD4A, 0x000A0001, 0x00000000) at 0xCBD10358
12676 - 2020-04-10 11:37:46,141 - INFO - File opened '/dev/log/main'
12676 - 2020-04-10 11:37:46,141 - INFO - openat return fd 15
12676 - 2020-04-10 11:37:46,141 - INFO - syscall 146 lr=0xCBD02441
12676 - 2020-04-10 11:37:46,141 - DEBUG - Executing syscall writev(0x0000000F, 0x100F0900, 0x00000003) at 0xCBD105CC
12676 - 2020-04-10 11:37:46,141 - INFO - Writev b'\x07'
12676 - 2020-04-10 11:37:46,141 - INFO - Writev b'libc\x00'
12676 - 2020-04-10 11:37:46,141 - INFO - Writev b':0: assertion "" failed\x00'
12676 - 2020-04-10 11:37:46,142 - INFO - syscall 6 lr=0xCBD02457
12676 - 2020-04-10 11:37:46,142 - DEBUG - Executing syscall close(0x0000000F) at 0xCBD1039C
12676 - 2020-04-10 11:37:46,142 - INFO - syscall 192 lr=0xCBD02C83
12676 - 2020-04-10 11:37:46,142 - DEBUG - Executing syscall mmap2(0x00000000, 0x0000001C, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBD1042C
map addr:0x00000000, end:0x0000001C, sz:0x0000001C off=0x00000000
before mem_map addr:0x302C5000, sz:0x00001000
mmap return 0x302C5000
12676 - 2020-04-10 11:37:46,284 - INFO - syscall 220 lr=0xCBD02C9F
12676 - 2020-04-10 11:37:46,284 - DEBUG - Executing syscall madvise(0x302C5000, 0x0000001C, 0x0000000C) at 0xCBD104CC
12676 - 2020-04-10 11:37:46,284 - INFO - syscall 126 lr=0xCBD01F1D
12676 - 2020-04-10 11:37:46,285 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0D2C) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,285 - INFO - syscall 67 lr=0xCBD01F43
12676 - 2020-04-10 11:37:46,285 - DEBUG - Executing syscall sigaction(0x00000006, 0x100F0D30, 0x100F0D30) at 0xCBD110D0
12676 - 2020-04-10 11:37:46,285 - WARNING - sa_handler [0x00000000] sa_mask [0x00000000] sa_flag [0x10000000] sa_restorer [0x100F0D64]
12676 - 2020-04-10 11:37:46,285 - INFO - syscall 126 lr=0xCBD01F4D
12676 - 2020-04-10 11:37:46,285 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0D2C) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,286 - INFO - syscall 248 lr=0xCBD01F59
12676 - 2020-04-10 11:37:46,286 - DEBUG - Executing syscall faccessat(0x00000001, 0x00000000, 0x00000001, 0x00000000) at 0xCBD0FD68
12676 - 2020-04-10 11:37:46,286 - INFO - faccessat filename:[]
12676 - 2020-04-10 11:37:46,287 - INFO - syscall 5 lr=0xCBD1D761
12676 - 2020-04-10 11:37:46,287 - DEBUG - Executing syscall open(0xCBD2FD4A, 0x000A0001, 0x00000000) at 0xCBD10358
12676 - 2020-04-10 11:37:46,287 - INFO - File opened '/dev/log/main'
12676 - 2020-04-10 11:37:46,287 - INFO - openat return fd 15
12676 - 2020-04-10 11:37:46,292 - INFO - syscall 146 lr=0xCBD02441
12676 - 2020-04-10 11:37:46,293 - DEBUG - Executing syscall writev(0x0000000F, 0x100F08A8, 0x00000003) at 0xCBD105CC
12676 - 2020-04-10 11:37:46,293 - INFO - Writev b'\x07'
12676 - 2020-04-10 11:37:46,293 - INFO - Writev b'libc\x00'
12676 - 2020-04-10 11:37:46,293 - INFO - Writev b':0: assertion "" failed\x00'
12676 - 2020-04-10 11:37:46,294 - INFO - syscall 6 lr=0xCBD02457
12676 - 2020-04-10 11:37:46,294 - DEBUG - Executing syscall close(0x0000000F) at 0xCBD1039C
12676 - 2020-04-10 11:37:46,296 - INFO - syscall 192 lr=0xCBD02C83
12676 - 2020-04-10 11:37:46,296 - DEBUG - Executing syscall mmap2(0x00000000, 0x0000001C, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBD1042C
map addr:0x00000000, end:0x0000001C, sz:0x0000001C off=0x00000000
before mem_map addr:0x302C6000, sz:0x00001000
mmap return 0x302C6000
12676 - 2020-04-10 11:37:46,440 - INFO - syscall 220 lr=0xCBD02C9F
12676 - 2020-04-10 11:37:46,440 - DEBUG - Executing syscall madvise(0x302C6000, 0x0000001C, 0x0000000C) at 0xCBD104CC
12676 - 2020-04-10 11:37:46,440 - INFO - syscall 126 lr=0xCBD01F1D
12676 - 2020-04-10 11:37:46,440 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0CD4) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,441 - INFO - syscall 67 lr=0xCBD01F43
12676 - 2020-04-10 11:37:46,441 - DEBUG - Executing syscall sigaction(0x00000006, 0x100F0CD8, 0x100F0CD8) at 0xCBD110D0
12676 - 2020-04-10 11:37:46,441 - WARNING - sa_handler [0x00000000] sa_mask [0x00000000] sa_flag [0x10000000] sa_restorer [0x100F0D0C]
12676 - 2020-04-10 11:37:46,441 - INFO - syscall 126 lr=0xCBD01F4D
12676 - 2020-04-10 11:37:46,441 - DEBUG - Executing syscall sigaltstack(0x00000002, 0x100F0CD4) at 0xCBD110F0
12676 - 2020-04-10 11:37:46,441 - INFO - syscall 248 lr=0xCBD01F59
12676 - 2020-04-10 11:37:46,441 - DEBUG - Executing syscall faccessat(0x00000001, 0x00000000, 0x00000001, 0x00000000) at 0xCBD0FD68
12676 - 2020-04-10 11:37:46,441 - INFO - faccessat filename:[]
12676 - 2020-04-10 11:37:46,443 - INFO - syscall 5 lr=0xCBD1D761
12676 - 2020-04-10 11:37:46,443 - DEBUG - Executing syscall open(0xCBD2FD4A, 0x000A0001, 0x00000000) at 0xCBD10358
12676 - 2020-04-10 11:37:46,443 - INFO - File opened '/dev/log/main'
12676 - 2020-04-10 11:37:46,443 - INFO - openat return fd 15
12676 - 2020-04-10 11:37:46,444 - INFO - syscall 146 lr=0xCBD02441
12676 - 2020-04-10 11:37:46,444 - DEBUG - Executing syscall writev(0x0000000F, 0x100F0850, 0x00000003) at 0xCBD105CC
12676 - 2020-04-10 11:37:46,451 - INFO - Writev b'\x07'
12676 - 2020-04-10 11:37:46,451 - INFO - Writev b'libc\x00'
12676 - 2020-04-10 11:37:46,451 - INFO - Writev b':0: assertion "" failed\x00'
12676 - 2020-04-10 11:37:46,451 - INFO - syscall 6 lr=0xCBD02457
12676 - 2020-04-10 11:37:46,452 - DEBUG - Executing syscall close(0x0000000F) at 0xCBD1039C
12676 - 2020-04-10 11:37:46,452 - INFO - syscall 192 lr=0xCBD02C83
12676 - 2020-04-10 11:37:46,452 - DEBUG - Executing syscall mmap2(0x00000000, 0x0000001C, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBD1042C
map addr:0x00000000, end:0x0000001C, sz:0x0000001C off=0x00000000
before mem_map addr:0x302C7000, sz:0x00001000
Assertion failed: (map->sections_nb < TARGET_PAGE_SIZE), function phys_section_add_arm, file /private/var/folders/84/y7q_xm292c99pxpf1mtjgjhw0000gn/T/pip-install-0h9tk2r5/unicorn/src/qemu/exec.c, line 798.
Abort trap: 6

------

**Comment by maiyao1988** [comment]
load library 直接崩溃可以试试手动将依赖项一个个load进来，以前曾经见过手动一个个load进来没问题，而递归load进来unicorn会崩的，这个问题暂时未知原因。
