### ISSUE TITLE
run example_douyin8.py   AttributeError: 'os.stat_result' object has no attribute 'st_rdev'

### ISSUE THREAD

**Issue by kingking888** [maiyao1988/ExAndroidNativeEmu#22]
D:\microsoft\python37\python.exe D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/example_douyin8.py
4152 - 2020-04-11 20:02:40,885 - INFO - process pid:4152
map addr:0x10000000, end:0x10100000, sz:0x00100000 off=0x00000000
stack addr 10100000
map addr:0x01000000, end:0x01200000, sz:0x00200000 off=0x00000000
4152 - 2020-04-11 20:02:41,643 - DEBUG - Loading module 'vfs/system/lib/libdvm.so'.
ok
map addr:0xCBBCB000, end:0xCBC71784, sz:0x000A6784 off=0x00000000
read for offset 0 sz 681860 data sz:681860
map addr:0xCBC72000, end:0xCBC72000, sz:0x00000000 off=0x00000000
map addr:0xCBC72000, end:0xCBC7A1C8, sz:0x000081C8 off=0x000A6000
read for offset 679936 sz 33224 data sz:33224
map addr:0xCBC7B000, end:0xCBC7D000, sz:0x00002000 off=0x00000000
4152 - 2020-04-11 20:02:41,655 - WARNING - libcorkscrew.so needed by vfs/system/lib/libdvm.so do not exist in vfs D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs
4152 - 2020-04-11 20:02:41,655 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libcutils.so'.
ok
map addr:0xCBC7D000, end:0xCBC85BA1, sz:0x00008BA1 off=0x00000000
read for offset 0 sz 35745 data sz:35745
map addr:0xCBC86000, end:0xCBC86000, sz:0x00000000 off=0x00000000
map addr:0xCBC86000, end:0xCBC8704C, sz:0x0000104C off=0x00008000
read for offset 32768 sz 4172 data sz:4172
map addr:0xCBC88000, end:0xCBC88000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,660 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/liblog.so'.
ok
map addr:0xCBC88000, end:0xCBC8AA4E, sz:0x00002A4E off=0x00000000
read for offset 0 sz 10830 data sz:10830
map addr:0xCBC8B000, end:0xCBC8B000, sz:0x00000000 off=0x00000000
map addr:0xCBC8B000, end:0xCBC8C018, sz:0x00001018 off=0x00002000
read for offset 8192 sz 4120 data sz:4120
map addr:0xCBC8D000, end:0xCBC8D000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,663 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so'.
ok
map addr:0xCBC8D000, end:0xCBCD3EF0, sz:0x00046EF0 off=0x00000000
read for offset 0 sz 290544 data sz:290544
map addr:0xCBCD4000, end:0xCBCD4000, sz:0x00000000 off=0x00000000
map addr:0xCBCD5000, end:0xCBCD92E8, sz:0x000042E8 off=0x00047000
read for offset 290816 sz 17128 data sz:17128
map addr:0xCBCDA000, end:0xCBCE8000, sz:0x0000E000 off=0x00000000
4152 - 2020-04-11 20:02:41,718 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libdl.so'.
ok
map addr:0xCBCE8000, end:0xCBCE9BE0, sz:0x00001BE0 off=0x00000000
read for offset 0 sz 7136 data sz:7136
map addr:0xCBCEA000, end:0xCBCEA000, sz:0x00000000 off=0x00000000
map addr:0xCBCEA000, end:0xCBCEB004, sz:0x00001004 off=0x00001000
read for offset 4096 sz 4100 data sz:4100
map addr:0xCBCEC000, end:0xCBCEC000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,723 - ERROR - => Undefined external symbol: 
4152 - 2020-04-11 20:02:41,723 - ERROR - => Undefined external symbol: __cxa_finalize
4152 - 2020-04-11 20:02:41,723 - ERROR - => Undefined external symbol: __cxa_atexit
4152 - 2020-04-11 20:02:41,723 - ERROR - => Undefined external symbol: memcpy
4152 - 2020-04-11 20:02:41,724 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libdl.so base 0xCBCE8000
4152 - 2020-04-11 20:02:41,724 - ERROR - => Undefined external symbol: 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBC9B2F9 
4152 - 2020-04-11 20:02:41,746 - INFO - syscall 5 lr=0xCBCBA761
4152 - 2020-04-11 20:02:41,747 - DEBUG - Executing syscall open(0xCBCD72E4, 0x000A8000, 0x00000000) at 0xCBCAD358
4152 - 2020-04-11 20:02:41,747 - WARNING - File does not exist '/dev/__properties__'
4152 - 2020-04-11 20:02:41,749 - INFO - syscall 240 lr=0xCBC9C020
4152 - 2020-04-11 20:02:41,749 - DEBUG - Executing syscall futex(0xCBCD9540, 0x00000081, 0x7FFFFFFF, 0x00000000, 0xCBCD9540, 0xCBC9AF05) at 0xCBCAE908
4152 - 2020-04-11 20:02:41,749 - INFO - futext call op=0x00000081 *uaddr=0x00000002 val=0x7FFFFFFF
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBC9FA51 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBC9FA65 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBCA0401 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBCA0539 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so function: 0xCBCB220D 
4152 - 2020-04-11 20:02:41,753 - INFO - syscall 263 lr=0xCBCB21B3
4152 - 2020-04-11 20:02:41,753 - DEBUG - Executing syscall clock_gettime(0x00000001, 0x100FFFE8) at 0xCBCADEA4
4152 - 2020-04-11 20:02:41,855 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libc.so base 0xCBC8D000
4152 - 2020-04-11 20:02:41,855 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libstdc++.so'.
ok
map addr:0xCBCEC000, end:0xCBCECAB1, sz:0x00000AB1 off=0x00000000
read for offset 0 sz 2737 data sz:2737
map addr:0xCBCED000, end:0xCBCED000, sz:0x00000000 off=0x00000000
map addr:0xCBCED000, end:0xCBCEE004, sz:0x00001004 off=0x00000000
read for offset 0 sz 4100 data sz:4100
map addr:0xCBCEF000, end:0xCBCEF000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,859 - ERROR - => Undefined external symbol: 
4152 - 2020-04-11 20:02:41,860 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libstdc++.so base 0xCBCEC000
4152 - 2020-04-11 20:02:41,860 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libm.so'.
ok
map addr:0xCBCEF000, end:0xCBD06EE4, sz:0x00017EE4 off=0x00000000
read for offset 0 sz 98020 data sz:98020
map addr:0xCBD07000, end:0xCBD07000, sz:0x00000000 off=0x00000000
map addr:0xCBD07000, end:0xCBD0806C, sz:0x0000106C off=0x00017000
read for offset 94208 sz 4204 data sz:4204
map addr:0xCBD09000, end:0xCBD09000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,890 - ERROR - => Undefined external symbol: 
4152 - 2020-04-11 20:02:41,891 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libm.so base 0xCBCEF000
4152 - 2020-04-11 20:02:41,891 - ERROR - => Undefined external symbol: 
4152 - 2020-04-11 20:02:41,892 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/liblog.so base 0xCBC88000
4152 - 2020-04-11 20:02:41,893 - ERROR - => Undefined external symbol: 
4152 - 2020-04-11 20:02:41,894 - INFO - finish load lib D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libcutils.so base 0xCBC7D000
4152 - 2020-04-11 20:02:41,894 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libnativehelper.so'.
ok
map addr:0xCBD09000, end:0xCBD0CAB0, sz:0x00003AB0 off=0x00000000
read for offset 0 sz 15024 data sz:15024
map addr:0xCBD0D000, end:0xCBD0D000, sz:0x00000000 off=0x00000000
map addr:0xCBD0D000, end:0xCBD0E004, sz:0x00001004 off=0x00003000
read for offset 12288 sz 4100 data sz:4100
map addr:0xCBD0F000, end:0xCBD0F000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,904 - DEBUG - Loading module 'D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libstlport.so'.
ok
map addr:0xCBD0F000, end:0xCBD403D0, sz:0x000313D0 off=0x00000000
read for offset 0 sz 201680 data sz:201680
map addr:0xCBD41000, end:0xCBD41000, sz:0x00000000 off=0x00000000
map addr:0xCBD41000, end:0xCBD43048, sz:0x00002048 off=0x00031000
read for offset 200704 sz 8264 data sz:8264
map addr:0xCBD44000, end:0xCBD44000, sz:0x00000000 off=0x00000000
4152 - 2020-04-11 20:02:41,992 - ERROR - => Undefined external symbol: 
Calling Init_array D:/PyhonProject/venv/Projects/fridahook/ExAndroidNativeEmu/vfs/system/lib/libstlport.so function: 0xCBD384E1 
4152 - 2020-04-11 20:02:42,030 - INFO - syscall 78 lr=0xCBCB21FD
4152 - 2020-04-11 20:02:42,030 - DEBUG - Executing syscall gettimeofday(0x100FFF48, 0x00000000) at 0xCBCADE24
4152 - 2020-04-11 20:02:42,032 - INFO - syscall 45 lr=0xCBCA021D
4152 - 2020-04-11 20:02:42,032 - DEBUG - Executing syscall brk(0x00000000) at 0xCBCAD0A0
4152 - 2020-04-11 20:02:42,032 - INFO - syscall 45 lr=0xCBCA022D
4152 - 2020-04-11 20:02:42,032 - DEBUG - Executing syscall brk(0xFFFFFFFF) at 0xCBCAD0A0
4152 - 2020-04-11 20:02:42,033 - INFO - syscall 192 lr=0xCBC9FC83
4152 - 2020-04-11 20:02:42,033 - DEBUG - Executing syscall mmap2(0x00000000, 0x00001000, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBCAD42C
map addr:0x00000000, end:0x00001000, sz:0x00001000 off=0x00000000
before mem_map addr:0x30000000, sz:0x00002000
mmap return 0x30000000
4152 - 2020-04-11 20:02:42,034 - INFO - syscall 220 lr=0xCBC9FC9F
4152 - 2020-04-11 20:02:42,034 - DEBUG - Executing syscall madvise(0x30000000, 0x00001000, 0x0000000C) at 0xCBCAD4CC
4152 - 2020-04-11 20:02:42,035 - INFO - syscall 172 lr=0xCBCBA6F7
4152 - 2020-04-11 20:02:42,035 - DEBUG - Executing syscall prctl(0x53564D41, 0x00000000, 0x30000000, 0x00001000, 0xCBCCCC52) at 0xCBCAD228
4152 - 2020-04-11 20:02:42,037 - INFO - syscall 192 lr=0xCBC9FC83
4152 - 2020-04-11 20:02:42,037 - DEBUG - Executing syscall mmap2(0x00000000, 0x00001000, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBCAD42C
map addr:0x00000000, end:0x00001000, sz:0x00001000 off=0x00000000
before mem_map addr:0x30002000, sz:0x00002000
mmap return 0x30002000
4152 - 2020-04-11 20:02:42,039 - INFO - syscall 220 lr=0xCBC9FC9F
4152 - 2020-04-11 20:02:42,039 - DEBUG - Executing syscall madvise(0x30002000, 0x00001000, 0x0000000C) at 0xCBCAD4CC
4152 - 2020-04-11 20:02:42,039 - INFO - syscall 125 lr=0xCBCB5747
4152 - 2020-04-11 20:02:42,039 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000001) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,044 - INFO - syscall 192 lr=0xCBC9FC83
4152 - 2020-04-11 20:02:42,045 - DEBUG - Executing syscall mmap2(0x00000000, 0x00002000, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBCAD42C
map addr:0x00000000, end:0x00002000, sz:0x00002000 off=0x00000000
before mem_map addr:0x30004000, sz:0x00003000
mmap return 0x30004000
4152 - 2020-04-11 20:02:42,046 - INFO - syscall 220 lr=0xCBC9FC9F
4152 - 2020-04-11 20:02:42,046 - DEBUG - Executing syscall madvise(0x30004000, 0x00002000, 0x0000000C) at 0xCBCAD4CC
4152 - 2020-04-11 20:02:42,046 - INFO - syscall 172 lr=0xCBCBA6F7
4152 - 2020-04-11 20:02:42,046 - DEBUG - Executing syscall prctl(0x53564D41, 0x00000000, 0x30004000, 0x00002000, 0xCBCCCC52) at 0xCBCAD228
4152 - 2020-04-11 20:02:42,095 - INFO - syscall 192 lr=0xCBC9FC83
4152 - 2020-04-11 20:02:42,095 - DEBUG - Executing syscall mmap2(0x00000000, 0x00001000, 0x00000003, 0x00000022, 0xFFFFFFFF, 0x00000000) at 0xCBCAD42C
map addr:0x00000000, end:0x00001000, sz:0x00001000 off=0x00000000
before mem_map addr:0x30007000, sz:0x00002000
mmap return 0x30007000
4152 - 2020-04-11 20:02:42,096 - INFO - syscall 220 lr=0xCBC9FC9F
4152 - 2020-04-11 20:02:42,097 - DEBUG - Executing syscall madvise(0x30007000, 0x00001000, 0x0000000C) at 0xCBCAD4CC
4152 - 2020-04-11 20:02:42,097 - INFO - syscall 172 lr=0xCBCBA6F7
4152 - 2020-04-11 20:02:42,097 - DEBUG - Executing syscall prctl(0x53564D41, 0x00000000, 0x30007000, 0x00001000, 0xCBCCCC52) at 0xCBCAD228
4152 - 2020-04-11 20:02:42,112 - INFO - syscall 125 lr=0xCBCB56E7
4152 - 2020-04-11 20:02:42,112 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000003) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,113 - INFO - syscall 125 lr=0xCBCB5747
4152 - 2020-04-11 20:02:42,113 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000001) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,114 - INFO - syscall 125 lr=0xCBCB56E7
4152 - 2020-04-11 20:02:42,114 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000003) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,115 - INFO - syscall 125 lr=0xCBCB5747
4152 - 2020-04-11 20:02:42,115 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000001) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,119 - INFO - syscall 125 lr=0xCBCB56E7
4152 - 2020-04-11 20:02:42,119 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000003) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,120 - INFO - syscall 125 lr=0xCBCB5747
4152 - 2020-04-11 20:02:42,121 - DEBUG - Executing syscall mprotect(0x30002000, 0x00001000, 0x00000001) at 0xCBCAD4AC
4152 - 2020-04-11 20:02:42,134 - INFO - syscall 221 lr=0xCBCB8C03
4152 - 2020-04-11 20:02:42,135 - DEBUG - Executing syscall fcntl64(0x00000000, 0x00000003, 0x00000008, 0x100FFF70, 0x30000B08, 0x00000000) at 0xCBCAD7D8
4152 - 2020-04-11 20:02:42,136 - INFO - syscall 197 lr=0xCBD26765
4152 - 2020-04-11 20:02:42,136 - DEBUG - Executing syscall fstat64(0x00000000, 0x100FFF08) at 0xCBCADAC8
4152 - 2020-04-11 20:02:42,136 - ERROR - An error occured during in c5 syscall hander, stopping emulation
Traceback (most recent call last):
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\vfs\file_system.py", line 262, in _handle_fstat64
    file_helpers.stat_to_memory2(mu, buf_ptr, stats, uid)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\vfs\file_helpers.py", line 76, in stat_to_memory2
    uc.mem_write(buf_ptr + 32, int(stat.st_rdev).to_bytes(8, byteorder='little'))
AttributeError: 'os.stat_result' object has no attribute 'st_rdev'
4152 - 2020-04-11 20:02:42,156 - ERROR - exception in _hook_interrupt intno:[2]
Traceback (most recent call last):
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\interrupt_handler.py", line 24, in _hook_interrupt
    self._handlers[intno](uc)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\cpu\syscall_handlers.py", line 43, in _handle_syscall
    result = handler.callback(mu, *args)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\vfs\file_system.py", line 262, in _handle_fstat64
    file_helpers.stat_to_memory2(mu, buf_ptr, stats, uid)
  File "D:\PyhonProject\venv\Projects\fridahook\ExAndroidNativeEmu\androidemu\vfs\file_helpers.py", line 76, in stat_to_memory2
    uc.mem_write(buf_ptr + 32, int(stat.st_rdev).to_bytes(8, byteorder='little'))
AttributeError: 'os.stat_result' object has no attribute 'st_rdev'

**Comment by maiyao1988** [comment]
I used linux api to implement syscall, not support windows right now

**Comment by maiyao1988** [comment]
fix
