### ISSUE TITLE
get_string_utf_chars 这个函数使用过后不释放内存，时间长，会崩溃

### ISSUE THREAD

**Issue by zbx911** [maiyao1988/ExAndroidNativeEmu#27]
get_string_utf_chars 这个函数使用过后不释放内存，时间长，会崩溃

**Comment by maiyao1988** [comment]
不是他不释放内存，应该是release_string_utf_chars 不干事导致的。。。

**Comment by zbx911** [comment]
@native_method
    def get_string_utf_chars(self, mu, env, string, is_copy_ptr):
        logger.debug("JNIEnv->GetStringUtfChars(%u, %x) was called" % (string, is_copy_ptr))

        if is_copy_ptr != 0:
            raise NotImplementedError()

        str_ref = self.get_reference(string)

        str_val=""

        if str_ref:
            str_obj = str_ref.value
            str_val = str_obj.get_py_string()



        最大内存宽度 = 0x10000
        if self.唯一注入内存地址==0:

            self.唯一注入内存地址 = self._emu.native_memory.allocate(最大内存宽度)

        logger.debug("=> %s" % str_val)



        mu.mem_write(self.唯一注入内存地址, bytes.fromhex("00")*(最大内存宽度-1))
        memory_helpers.write_utf8(mu, self.唯一注入内存地址, str_val)

        return self.唯一注入内存地址

**Comment by zbx911** [comment]
参数写入后需要释放内存

**Comment by maiyao1988** [comment]
最新版本已经实现release_string_utf_chars，如果原so没有调用release_string_utf_chars，依然会导致泄漏
