### ISSUE TITLE
navtive对数字进行传参的时候为空

### ISSUE THREAD

**Issue by zbx911** [maiyao1988/ExAndroidNativeEmu#29]
navtive对数字进行传参的时候为空

**Comment by maiyao1988** [comment]
麻烦给出示例，最好能给出复现代码

**Comment by zbx911** [comment]
main_activity.getSignData(self.emulator, String(d), 1) 第二个参数是1，写入的时候是r3，单调用的时候，r3为0

**Comment by maiyao1988** [comment]
> main_activity.getSignData(self.emulator, String(d), 1) 第二个参数是1，写入的时候是r3，单调用的时候，r3为0

没理解意思，为何第二个参数会是r3,如果认为有bug的话，给出复现的脚本吧。
