### ISSUE TITLE
X-Gorgon Signature For Tiktok

### ISSUE THREAD

**Issue by itsecres-nandant** [maiyao1988/ExAndroidNativeEmu#39]
I really appreciate for your great work towards open source community :)

can you please write one example for tiktok app (international version of douyin) also? to generate x-gorgon value?

thanks in advance <3

**Comment by maiyao1988** [comment]
xg is not an easy job ，need reverse engineering

**Comment by xgorgon** [comment]
@itsecres-nandant

I can sell script to generate xgorgon header contact me at xgorgon@protonmail.com or telegram https://t.me/adotdaniel
