### ISSUE TITLE
运行速度有优化空间吗

### ISSUE THREAD

**Issue by snfnwgi** [maiyao1988/ExAndroidNativeEmu#4]
请教一下，在我本地脚本运行时间大概2秒种左右，有什么好的方式提升性能吗，感谢！

**Comment by maiyao1988** [comment]
you can reduce hooks, like hook_code，hook_memory,thses hook is tracing every instruction,so it is very slow.
for example, you can remove example_jni.py line 85 87 88, this hooks is just for debug.

**Comment by snfnwgi** [comment]
Thank you, I used the example_doyin.py called, this is very slow, there is no hook instruction in it, which one should be removed?

**Comment by maiyao1988** [comment]
> Thank you, I used the example_doyin.py called, this is very slow, there is no hook instruction in it, which one should be removed?

example_douyin.py is a very large function,now there is no better way to optimize this.
this so is a extremely case...

**Comment by harrisonwhiskey** [comment]
@maiyao1988 this is not a bug report and i didn't know where else to post this.
the example_doyin.py is using old libcms.so, it works alright but i want to know is it possible to emulate newer versions of libcms.so?

If i want to emulate a newer version of libcms.so what do i need to know or learn to get started?. I hope you can point me in the right direction to learn and take full advantage of this library.

**Comment by maiyao1988** [comment]
@harrisonwhiskey  I heard that new version of libcms.so native signature has change, exspecially function leviathan .you should check the signature.make sure the signature is right, In theory It will be ok to simulate other so.if  FindClass/GetMethod report some class or method not found, just add a fake class and do the simplest implementation of the used method like the example.
 
actually I didn't analyze libcms.so too much, just treat it as a complex test example, and make the simulate pass.
