### ISSUE TITLE
can not detect nsymbol by DT_HASH, DT_GNUHASH, not support now

### ISSUE THREAD

**Issue by hpp0hpp** [maiyao1988/ExAndroidNativeEmu#43]
seems your elf reader has some problem.

这个现在还不支持吗？同样的so， 原生AndroidNativeEmu就可以加载

**Comment by maiyao1988** [comment]
AndroidNativeEmu能加载的原因是他拿section header来加载的, 如果section header被破坏是无法加载的, 用DT_GNUHASH去读symbols个数需要到这个结构进行解析, 这个我暂时还没做. 或者你可以先将so放上来,我有时间看看.

**Comment by hpp0hpp** [comment]
> AndroidNativeEmu能加载的原因是他拿section header来加载的, 如果section header被破坏是无法加载的, 用DT_GNUHASH去读symbols个数需要到这个结构进行解析, 这个我暂时还没做. 或者你可以先将so放上来,我有时间看看.
> 
> 只有DT_GNUHASH的so一般存在在android5.0以上的so,andorid4.4 是无法识别DT_GNUHASH结构的.

嗯嗯,下面是这个so

[libliar.zip](https://github.com/maiyao1988/ExAndroidNativeEmu/files/5925918/libliar.zip)

**Comment by maiyao1988** [comment]
fix in 56b592187d744a41191944741e91c66554ae3fb7
