### ISSUE TITLE
Can you add fprintf?

### ISSUE THREAD

**Issue by JReverse** [maiyao1988/ExAndroidNativeEmu#49]
Can you add fprintf?

**Comment by maiyao1988** [comment]
why you need special hook for fprintf? It's unnecessary,because the libc is already loaded. just use libc implement is ok.

**Comment by JReverse** [comment]
@maiyao1988     raise NotImplementedError('Symbol hook not implemented %s' % name)
NotImplementedError: Symbol hook not implemented fprintf

**Comment by maiyao1988** [comment]
who hook fprintf? I don't hook fprintf in my code,it will be well handled by libc.so
