### ISSUE TITLE
加载类问题

### ISSUE THREAD

**Issue by pujie1216** [maiyao1988/ExAndroidNativeEmu#50]
某些app在特定类中需要增加函数,例如需要在Activity类里增加一个函数,然而ExAndroidNativeEmu貌似只使用程序定义的Activity类,导致RuntimeError,我尝试在自己的代码中自定义Activity类,然后 add_class 加载,运行后提示: The class 'android/app/Activity' is already registered. 屏蔽 add_class 语句则返回相同的提示: RuntimeError: Could not find method ('getPackageManager', '()Landroid/content/pm/PackageManager;') in class android/app/Activity. 可能不止这个Activity类,Application类等也会出现这个情况,目前没有找到能解决这个情况的文档,希望作者大大能帮忙解答一下:(

**Comment by maiyao1988** [comment]
android/app/Activity 是一个系统类，一个正常的应用可能在android/app/Activity 加任何自定义的东西，至于他自己搞了什么Activity，自己添加对应的类型 add进去就可以，already  registered是由于你加了两个一样签名的Activity。

**Comment by pujie1216** [comment]
这个错误提示不是明确返回 in class android/app/Activity 吗?添加的 jvm_name 一旦不是 android/app/Activity 的话,依然会返回相同的错误提示啊

**Comment by maiyao1988** [comment]
首先，除非他用到android/app/Activity我没写到的方法 系统标准方法，你可以到android/app/Activity里面加，如果不是系统标准方法，那么他必定不是android/app/Activity 而是其他签名。懂意思就好。
