### ISSUE TITLE
想请教下call_native的时候call addr is None是什么情况导致的

### ISSUE THREAD

**Issue by owlwang** [maiyao1988/ExAndroidNativeEmu#51]
代码和so见附件。
[crack.zip](https://github.com/maiyao1988/ExAndroidNativeEmu/files/6590135/crack.zip)

实现完类之后
调用的时候发现native_wrapper.jvm_method.native_addr的值为None 所以导致emulator.call_native()的时候会直接异常退出 『call addr is None』
当我直接调用emulator.call_symbol的时候 有报错
『RuntimeError: Could not find method 3523215512 in object android/app/ContextImpl by id.』

也将so里面的symbol打印出来看过，是加载进去的。
load symbols tests/bin/libxxx_utils.so {'name': 'Java_xxx_xxx_xxx_xxx_XXXUtil_init', 'st_name': 184, 'st_value': 53361, 'st_size': 340, 'st_info': b'\x12', 'st_other': b'\x00', 'st_shndx': 12, 'st_info_bind': 1, 'st_info_type': 2}
load symbols tests/bin/libxxx_utils.so {'name': 'Java_xxx_xxx_xxx_xxx_XXXUtil_decryptResponse', 'st_name': 750, 'st_value': 54529, 'st_size': 416, 'st_info': b'\x12', 'st_other': b'\x00', 'st_shndx': 12, 'st_info_bind': 1, 'st_info_type': 2}

想问下这两种情况分别是为啥导致的，有啥解决方法嘛？

```python
import logging
import posixpath

from androidemu.emulator import Emulator
from androidemu.java.classes.activity_thread import ActivityThread
from androidemu.java.java_class_def import JavaClassDef
from androidemu.java.java_method_def import java_method_def


class XXXUtil(metaclass=JavaClassDef, jvm_name='com/xxx/xxxx/xxx/XXXUtil'):
    def __init__(self):
        pass

    @java_method_def(name='init', signature='(Landroid/content/Context;)Ljava/lang/String;', native=True)
    def init(self, mu):
        pass

    @java_method_def(name='decryptResponse', signature='(Ljava/lang/String;)Ljava/lang/String;', native=True)
    def decryptResponse(self, mu):
        pass


logger = logging.getLogger(__name__)

emulator = Emulator(
    vfp_inst_set=True,
    vfs_root=posixpath.join(posixpath.dirname(__file__), "vfs")
)

emulator.java_classloader.add_class(FDLUtil)

lib_module = emulator.load_library("tests/bin/libxxx.so")
at = ActivityThread()
ctx = at.getSystemContext(emulator)

xxx = XXXUtil()
res = xxx.init(emulator, ctx)
print(res)
emulator.call_symbol(module, 'Java_com_xxx_xxx_xxx_XXXUtil_init', emulator.java_vm.jni_env.address_ptr,  0x00, ctx)

```

**Comment by owlwang** [comment]
第一个手动注册之后确实可以正常调用了。
第二个改成获取currentApplication也可以正常调用了。
两种方法都可以，nb.

这个 so 好像是需要init 获取包名然后进行一些操作然后才可以正常使用encrypt decrypt
但是 目前又遇到了一个问题 decryptResponse 方法还是没法解出正常的内容，返回的是乱码。
这种情况是否是so里面做了检测措施导致的？能请教下有什么思路可以解决这种问题?
（见附件）

[crack.zip](https://github.com/maiyao1988/ExAndroidNativeEmu/files/6596777/crack.zip)

**Comment by maiyao1988** [comment]
你打开日志看他调用了什么android 函数和系统调用，看看是否有签名相关调用。这个需要凭一点经验。

**Comment by owlwang** [comment]
感谢帮助, 我研究研究。
thx
