### ISSUE TITLE
douyin example run failure

### ISSUE THREAD

**Issue by newthis** [maiyao1988/ExAndroidNativeEmu#52]
It seems that the JavaMethodDef's native_addr is always None, and this is confusing.

![douyin](https://user-images.githubusercontent.com/9391505/132328807-bae52a20-67b7-45ab-ab5c-1144805de9d7.JPG)
![douyin2](https://user-images.githubusercontent.com/9391505/132328835-0e39c2a7-d179-404f-ba99-a8d2ab30c13e.JPG)

**Comment by maiyao1988** [comment]
不要使用unicorn 1.0.3这是unicorn最新版本的bug

**Comment by FatsharkGo** [comment]
感谢回复！

使用python3.7.9和requirements.txt中声明的unicorn 1.0.1跑`example_jni.py`没有异常了，调用栈可以观察到`native_addr`字段被更新了。

话说在Win10下pyenv is totally a shit!

**Comment by FatsharkGo** [comment]
这个项目非常棒，@maiyao1988是否有考虑将修改PR到[AndroidNativeEmu](https://github.com/AeonLucid/AndroidNativeEmu)？

**Comment by maiyao1988** [comment]
> 这个项目非常棒，@maiyao1988是否有考虑将修改PR到[AndroidNativeEmu](https://github.com/AeonLucid/AndroidNativeEmu)？

我改得有点大有点难 pr了 那边有什么修改重要的的我会同步过来

**Comment by xgorgon** [comment]
@newthis if you need xgorgon you can mail me at xgorgon@protonmail.com
