### ISSUE TITLE
Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by syferdev29** [maiyao1988/ExAndroidNativeEmu#53]
since the last update, the emulator gives the same error in running modules

![image](https://user-images.githubusercontent.com/43702683/151714772-99f4d4be-a774-4c2f-aeea-dc400062841c.png)

**Comment by maiyao1988** [comment]
which unicorn are you using? it is no  error on linux with unicorn1.0.2

**Comment by syferdev29** [comment]
unicorn 1.0.1

**Comment by LLeavesG** [comment]
The same error report happend to me, and I try every unicorn version but not success.

**Comment by maiyao1988** [comment]
Are you using windows? I only test it on mac or linux.

**Comment by maiyao1988** [comment]
sorry, forget to commit some important file. update and It should be ok now.

**Comment by LLeavesG** [comment]
thanks for your good work, the new version can't work also at begin,but when i replace the libc.so in vsf/system/lib that it can be work well.

**Comment by maiyao1988** [comment]
> thanks for your good work, the new version can't work also at begin,but when i replace the libc.so in vsf/system/lib that it can be work well.

what so are you simulating?All the tests pass with the libc in vfs/, is it new situation I haven't met yet?
what happens if you run python3 -m unittest tests/*.py in your enviroment?

**Comment by LLeavesG** [comment]
我在windows上进行了测试，如果使用unicorn1.0.1，解释执行test_native报错如下，WSL2-ubuntu下报类似的错误

```python
ERROR: test_tls32 (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 90, in test_tls32
    libcm = emulator.load_library("vfs/system/lib/libc.so")
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 248, in load_library
    libmod = self.modules.load_module(filename, True)
  File "E:\pythoncode\ExAndroidEmu\androidemu\internal\modules.py", line 489, in load_module
    module.call_init(self.emu)
  File "E:\pythoncode\ExAndroidEmu\androidemu\internal\module.py", line 45, in call_init
    emu.call_native(fun_addr)
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 265, in __call_native32
    self.__sch.exec(addr)
  File "E:\pythoncode\ExAndroidEmu\androidemu\scheduler.py", line 288, in exec
    self.__emu.mu.emu_start(start_pos, self.__stop_pos, 0, 0)
  File "E:\Anaconda3\lib\site-packages\unicorn\unicorn.py", line 288, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 93, in test_tls32
    print("Exit at 0x%08X" % emulator.mu.reg_read(UC_ARM_REG_PC))
NameError: name 'UC_ARM_REG_PC' is not defined

======================================================================
ERROR: test_tls64 (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 101, in test_tls64
    emulator = Emulator(
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
    self.__enable_vfp64()
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
    x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.098s
```
当我替换libc后它报错如下，但是不报这个`Invalid memory read (UC_ERR_READ_UNMAPPED)`错，能够满足ARM32位so模拟需求

```python
EEEERROR:androidemu.internal.modules:=> Undefined external symbol: 
ERROR:androidemu.internal.modules:=> Undefined external symbol: __cxa_finalize
ERROR:androidemu.internal.modules:=> Undefined external symbol: __cxa_atexit
ERROR:androidemu.internal.modules:=> Undefined external symbol: memcpy
ERROR:androidemu.internal.modules:=> Undefined external symbol: 
ERROR:androidemu.internal.modules:=> Undefined external symbol: android_get_application_target_sdk_versionERROR:androidemu.internal.modules:=> Undefined external symbol: .E
======================================================================
ERROR: test_64_elf (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 118, in test_64_elf
    emulator = Emulator(
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
    self.__enable_vfp64()
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
    x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined

======================================================================
ERROR: test_load_bias_new_delete (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 145, in test_load_bias_new_delete
    emulator = Emulator(
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
    self.__enable_vfp64()
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
    x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined

======================================================================
ERROR: test_something (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 54, in test_something
    module = emulator.load_library(posixpath.join(posixpath.dirname(__file__), "bin", "test_native.so"))
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 248, in load_library
    libmod = self.modules.load_module(filename, True)
  File "E:\pythoncode\ExAndroidEmu\androidemu\internal\modules.py", line 231, in load_module
    reader = elf_reader.ELFReader(filename)
  File "E:\pythoncode\ExAndroidEmu\androidemu\internal\elf_reader.py", line 164, in __init__
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'bin/test_native.so'

======================================================================
ERROR: test_tls64 (tests.test_native.TestNative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 101, in test_tls64
    emulator = Emulator(
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
    self.__enable_vfp64()
  File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
    x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.156s

FAILED (errors=4)
```

**Comment by LLeavesG** [comment]
我顺便比较了两个libc
![image](https://user-images.githubusercontent.com/57952228/153123483-085eda2f-b94d-44ee-9eb1-4f54e51774e5.png)
右边是我替换的，

**Comment by maiyao1988** [comment]
> 我在windows上进行了测试，如果使用unicorn1.0.1，解释执行test_native报错如下，WSL2-ubuntu下报类似的错误
> 
> ```python
> ERROR: test_tls32 (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 90, in test_tls32
>     libcm = emulator.load_library("vfs/system/lib/libc.so")
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 248, in load_library
>     libmod = self.modules.load_module(filename, True)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\internal\modules.py", line 489, in load_module
>     module.call_init(self.emu)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\internal\module.py", line 45, in call_init
>     emu.call_native(fun_addr)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 265, in __call_native32
>     self.__sch.exec(addr)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\scheduler.py", line 288, in exec
>     self.__emu.mu.emu_start(start_pos, self.__stop_pos, 0, 0)
>   File "E:\Anaconda3\lib\site-packages\unicorn\unicorn.py", line 288, in emu_start
>     raise UcError(status)
> unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 93, in test_tls32
>     print("Exit at 0x%08X" % emulator.mu.reg_read(UC_ARM_REG_PC))
> NameError: name 'UC_ARM_REG_PC' is not defined
> 
> ======================================================================
> ERROR: test_tls64 (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 101, in test_tls64
>     emulator = Emulator(
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
>     self.__enable_vfp64()
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
>     x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
> NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined
> 
> ----------------------------------------------------------------------
> Ran 5 tests in 0.098s
> ```
> 
> 当我替换libc后它报错如下，但是不报这个`Invalid memory read (UC_ERR_READ_UNMAPPED)`错，能够满足ARM32位so模拟需求
> 
> ```python
> EEEERROR:androidemu.internal.modules:=> Undefined external symbol: 
> ERROR:androidemu.internal.modules:=> Undefined external symbol: __cxa_finalize
> ERROR:androidemu.internal.modules:=> Undefined external symbol: __cxa_atexit
> ERROR:androidemu.internal.modules:=> Undefined external symbol: memcpy
> ERROR:androidemu.internal.modules:=> Undefined external symbol: 
> ERROR:androidemu.internal.modules:=> Undefined external symbol: android_get_application_target_sdk_versionERROR:androidemu.internal.modules:=> Undefined external symbol: .E
> ======================================================================
> ERROR: test_64_elf (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 118, in test_64_elf
>     emulator = Emulator(
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
>     self.__enable_vfp64()
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
>     x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
> NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined
> 
> ======================================================================
> ERROR: test_load_bias_new_delete (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 145, in test_load_bias_new_delete
>     emulator = Emulator(
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
>     self.__enable_vfp64()
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
>     x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
> NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined
> 
> ======================================================================
> ERROR: test_something (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 54, in test_something
>     module = emulator.load_library(posixpath.join(posixpath.dirname(__file__), "bin", "test_native.so"))
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 248, in load_library
>     libmod = self.modules.load_module(filename, True)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\internal\modules.py", line 231, in load_module
>     reader = elf_reader.ELFReader(filename)
>   File "E:\pythoncode\ExAndroidEmu\androidemu\internal\elf_reader.py", line 164, in __init__
>     with open(filename, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'bin/test_native.so'
> 
> ======================================================================
> ERROR: test_tls64 (tests.test_native.TestNative)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "E:\pythoncode\ExAndroidEmu\tests\test_native.py", line 101, in test_tls64
>     emulator = Emulator(
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 153, in __init__
>     self.__enable_vfp64()
>   File "E:\pythoncode\ExAndroidEmu\androidemu\emulator.py", line 87, in __enable_vfp64
>     x = self.mu.reg_read(UC_ARM64_REG_CPACR_EL1)
> NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined
> 
> ----------------------------------------------------------------------
> Ran 5 tests in 0.156s
> 
> FAILED (errors=4)
> ```

unicorn 1.01 do not support some arm64 register, should use 1.02 or later. bug not test in 2.0+

**Comment by LLeavesG** [comment]
> 

Thanks again, unicorn 1.2 can work great.And Invalid memory read (UC_ERR_READ_UNMAPPED) still reported when i use the libc provided in the raw project , and it's strange that the exmaple in project also report UC_ERR_READ_UNMAPPED error, maybe the libc i found in my phone better fit for my device(I don't know the reasons).

**Comment by LLeavesG** [comment]
Thanks again, unicorn 1.02 can work great.And Invalid memory read (UC_ERR_READ_UNMAPPED) still reported when i use the libc provided in the raw project , and it's strange that the exmaple in project also report UC_ERR_READ_UNMAPPED error, maybe the libc i found in my phone better fit for my device(I don't know the reasons).

**Comment by maiyao1988** [comment]
你用的的哪个安卓版本的libc?

**Comment by LLeavesG** [comment]
我直接用的AndroidNativeEmu项目examples\example_binaries\32下面的libc

**Comment by maiyao1988** [comment]
gitflow has add , all tests should be run after push to advoid missing import file.

**Comment by Harvey-2021** [comment]
我刚克隆的项目，运行example_jni.py，还是报同样的错误！
python版本 3.7.4
![image](https://user-images.githubusercontent.com/52552891/159476836-2951bd36-73d6-43f1-9731-a99d344eef38.png)

**Comment by hpp0hpp** [comment]
example_jni 仍然需要换一个libc.so才可以运行

**Comment by Harvey-2021** [comment]
只是windows上有问题，linux work well

**Comment by Harvey-2021** [comment]
[ins-jni.txt](https://github.com/maiyao1988/ExAndroidNativeEmu/files/8331362/ins-jni.txt)
