### ISSUE TITLE
如何加载libandroid.so

### ISSUE THREAD

**Issue by weststarqp** [maiyao1988/ExAndroidNativeEmu#9]
感谢大佬的项目,我现在遇到个问题,由于目标so需要调用AAssetManager_fromJava,我尝试让它加载libandroid.so,提示
"can not detect nsymbol by DT_HASH, DT_GNUHASH, not support now"

**Comment by maiyao1988** [comment]
AAssetManager_fromJava是libAndroid的符号吗？libAndroid从什么系统复制进来的，最好不要找5.0以上的系统，因为5.0以上的符号hash表可能会使用gnu hash，我这里暂时还没写解析代码，用4.4的应该就不会出现了

**Comment by weststarqp** [comment]
换了4.4.4的可以使用了,十分感谢.
